add_requires("catch2")
target("cpp-toolbox-tests")
        set_kind("binary")
        add_files(test_files)
        add_deps("cpp-toolbox_static")
        add_packages("catch2")
        add_rules("generate_export_header")
        set_pcxxheader("src/impl/cpp-toolbox/pch.hpp")
        set_policy("build.optimization.lto", true)