var annotated_dup =
[
    [ "toolbox", "namespacetoolbox.html", [
      [ "base", "namespacetoolbox_1_1base.html", [
        [ "detail", "namespacetoolbox_1_1base_1_1detail.html", [
          [ "task_base", "structtoolbox_1_1base_1_1detail_1_1task__base.html", "structtoolbox_1_1base_1_1detail_1_1task__base" ],
          [ "task_derived", "structtoolbox_1_1base_1_1detail_1_1task__derived.html", "structtoolbox_1_1base_1_1detail_1_1task__derived" ]
        ] ],
        [ "memory_pool_t", "classtoolbox_1_1base_1_1memory__pool__t.html", "classtoolbox_1_1base_1_1memory__pool__t" ],
        [ "object_pool_t", "classtoolbox_1_1base_1_1object__pool__t.html", "classtoolbox_1_1base_1_1object__pool__t" ],
        [ "PoolDeleter", "classtoolbox_1_1base_1_1_pool_deleter.html", "classtoolbox_1_1base_1_1_pool_deleter" ],
        [ "thread_pool_singleton_t", "classtoolbox_1_1base_1_1thread__pool__singleton__t.html", "classtoolbox_1_1base_1_1thread__pool__singleton__t" ],
        [ "thread_pool_t", "classtoolbox_1_1base_1_1thread__pool__t.html", "classtoolbox_1_1base_1_1thread__pool__t" ]
      ] ],
      [ "container", "namespacetoolbox_1_1container.html", [
        [ "detail", "namespacetoolbox_1_1container_1_1detail.html", [
          [ "HazardPointerGuard", "classtoolbox_1_1container_1_1detail_1_1_hazard_pointer_guard.html", "classtoolbox_1_1container_1_1detail_1_1_hazard_pointer_guard" ],
          [ "HPRec", "structtoolbox_1_1container_1_1detail_1_1_h_p_rec.html", "structtoolbox_1_1container_1_1detail_1_1_h_p_rec" ]
        ] ],
        [ "concurrent_queue_t", "classtoolbox_1_1container_1_1concurrent__queue__t.html", "classtoolbox_1_1container_1_1concurrent__queue__t" ],
        [ "lock_free_queue_t", "classtoolbox_1_1container_1_1lock__free__queue__t.html", "classtoolbox_1_1container_1_1lock__free__queue__t" ]
      ] ],
      [ "file", "namespacetoolbox_1_1file.html", [
        [ "memory_mapped_file_t", "classtoolbox_1_1file_1_1memory__mapped__file__t.html", "classtoolbox_1_1file_1_1memory__mapped__file__t" ]
      ] ],
      [ "functional", "namespacetoolbox_1_1functional.html", [
        [ "detail", "namespacetoolbox_1_1functional_1_1detail.html", [
          [ "has_size", "structtoolbox_1_1functional_1_1detail_1_1has__size.html", null ],
          [ "has_size< T, std::void_t< decltype(std::declval< T >().size())> >", "structtoolbox_1_1functional_1_1detail_1_1has__size_3_01_t_00_01std_1_1void__t_3_01decltype_07std431779fbfc2ce525a80568a6245b1d79.html", null ],
          [ "is_optional", "structtoolbox_1_1functional_1_1detail_1_1is__optional.html", null ],
          [ "is_optional< std::optional< T > >", "structtoolbox_1_1functional_1_1detail_1_1is__optional_3_01std_1_1optional_3_01_t_01_4_01_4.html", null ],
          [ "MemoizeState", "structtoolbox_1_1functional_1_1detail_1_1_memoize_state.html", "structtoolbox_1_1functional_1_1detail_1_1_memoize_state" ],
          [ "overloaded", "structtoolbox_1_1functional_1_1detail_1_1overloaded.html", null ]
        ] ],
        [ "detail_impl", "namespacetoolbox_1_1functional_1_1detail__impl.html", [
          [ "MemoizeHelperState", "structtoolbox_1_1functional_1_1detail__impl_1_1_memoize_helper_state.html", "structtoolbox_1_1functional_1_1detail__impl_1_1_memoize_helper_state" ]
        ] ],
        [ "MemoizedFunction< R(Args...)>", "classtoolbox_1_1functional_1_1_memoized_function_3_01_r_07_args_8_8_8_08_4.html", "classtoolbox_1_1functional_1_1_memoized_function_3_01_r_07_args_8_8_8_08_4" ]
      ] ],
      [ "io", "namespacetoolbox_1_1io.html", [
        [ "base_file_data_t", "classtoolbox_1_1io_1_1base__file__data__t.html", "classtoolbox_1_1io_1_1base__file__data__t" ],
        [ "base_file_format_t", "classtoolbox_1_1io_1_1base__file__format__t.html", "classtoolbox_1_1io_1_1base__file__format__t" ],
        [ "dataloader_t", "classtoolbox_1_1io_1_1dataloader__t.html", "classtoolbox_1_1io_1_1dataloader__t" ],
        [ "dataset_t", "classtoolbox_1_1io_1_1dataset__t.html", "classtoolbox_1_1io_1_1dataset__t" ],
        [ "kitti_format_t", "classtoolbox_1_1io_1_1kitti__format__t.html", "classtoolbox_1_1io_1_1kitti__format__t" ],
        [ "kitti_pcd_dataset_t", "classtoolbox_1_1io_1_1kitti__pcd__dataset__t.html", "classtoolbox_1_1io_1_1kitti__pcd__dataset__t" ],
        [ "kitti_pcd_pair_t", "classtoolbox_1_1io_1_1kitti__pcd__pair__t.html", "classtoolbox_1_1io_1_1kitti__pcd__pair__t" ],
        [ "pcd_format_t", "classtoolbox_1_1io_1_1pcd__format__t.html", "classtoolbox_1_1io_1_1pcd__format__t" ],
        [ "sampler_t", "classtoolbox_1_1io_1_1sampler__t.html", "classtoolbox_1_1io_1_1sampler__t" ],
        [ "sequential_policy_t", "structtoolbox_1_1io_1_1sequential__policy__t.html", "structtoolbox_1_1io_1_1sequential__policy__t" ],
        [ "shuffle_policy_t", "classtoolbox_1_1io_1_1shuffle__policy__t.html", "classtoolbox_1_1io_1_1shuffle__policy__t" ]
      ] ],
      [ "logger", "namespacetoolbox_1_1logger.html", [
        [ "has_ostream_method", "structtoolbox_1_1logger_1_1has__ostream__method.html", null ],
        [ "has_stream_operator", "structtoolbox_1_1logger_1_1has__stream__operator.html", null ],
        [ "is_container", "structtoolbox_1_1logger_1_1is__container.html", null ],
        [ "is_container< T, std::void_t< T::value_type, T::iterator, decltype(std::declval< T >().begin()), decltype(std::declval< T >().end())> >", "structtoolbox_1_1logger_1_1is__container_3_01_t_00_01std_1_1void__t_3_01_t_1_1value__type_00_01_1041f7af6953dcde600448a7d1be57a1.html", null ],
        [ "thread_logger_t", "classtoolbox_1_1logger_1_1thread__logger__t.html", "classtoolbox_1_1logger_1_1thread__logger__t" ]
      ] ],
      [ "metrics", "namespacetoolbox_1_1metrics.html", [
        [ "AngularMetric", "classtoolbox_1_1metrics_1_1_angular_metric.html", "classtoolbox_1_1metrics_1_1_angular_metric" ],
        [ "base_metric_t", "classtoolbox_1_1metrics_1_1base__metric__t.html", "classtoolbox_1_1metrics_1_1base__metric__t" ],
        [ "BhattacharyyaMetric", "classtoolbox_1_1metrics_1_1_bhattacharyya_metric.html", "classtoolbox_1_1metrics_1_1_bhattacharyya_metric" ],
        [ "BoundingBoxMetric", "classtoolbox_1_1metrics_1_1_bounding_box_metric.html", "classtoolbox_1_1metrics_1_1_bounding_box_metric" ],
        [ "CentroidMetric", "classtoolbox_1_1metrics_1_1_centroid_metric.html", "classtoolbox_1_1metrics_1_1_centroid_metric" ],
        [ "ChamferMetric", "classtoolbox_1_1metrics_1_1_chamfer_metric.html", "classtoolbox_1_1metrics_1_1_chamfer_metric" ],
        [ "ChiSquaredMetric", "classtoolbox_1_1metrics_1_1_chi_squared_metric.html", "classtoolbox_1_1metrics_1_1_chi_squared_metric" ],
        [ "CompositeMetric", "classtoolbox_1_1metrics_1_1_composite_metric.html", "classtoolbox_1_1metrics_1_1_composite_metric" ],
        [ "CorrelationMetric", "classtoolbox_1_1metrics_1_1_correlation_metric.html", "classtoolbox_1_1metrics_1_1_correlation_metric" ],
        [ "CosineMetric", "classtoolbox_1_1metrics_1_1_cosine_metric.html", "classtoolbox_1_1metrics_1_1_cosine_metric" ],
        [ "CustomMetric", "classtoolbox_1_1metrics_1_1_custom_metric.html", "classtoolbox_1_1metrics_1_1_custom_metric" ],
        [ "EMDMetric", "classtoolbox_1_1metrics_1_1_e_m_d_metric.html", "classtoolbox_1_1metrics_1_1_e_m_d_metric" ],
        [ "GeneralizedLpMetric", "classtoolbox_1_1metrics_1_1_generalized_lp_metric.html", "classtoolbox_1_1metrics_1_1_generalized_lp_metric" ],
        [ "HausdorffMetric", "classtoolbox_1_1metrics_1_1_hausdorff_metric.html", "classtoolbox_1_1metrics_1_1_hausdorff_metric" ],
        [ "HellingerMetric", "classtoolbox_1_1metrics_1_1_hellinger_metric.html", "classtoolbox_1_1metrics_1_1_hellinger_metric" ],
        [ "HistogramIntersectionMetric", "classtoolbox_1_1metrics_1_1_histogram_intersection_metric.html", "classtoolbox_1_1metrics_1_1_histogram_intersection_metric" ],
        [ "IMetric", "classtoolbox_1_1metrics_1_1_i_metric.html", "classtoolbox_1_1metrics_1_1_i_metric" ],
        [ "InnerProductMetric", "classtoolbox_1_1metrics_1_1_inner_product_metric.html", "classtoolbox_1_1metrics_1_1_inner_product_metric" ],
        [ "is_metric", "structtoolbox_1_1metrics_1_1is__metric.html", null ],
        [ "is_metric< base_metric_t< Derived, ElementType > >", "structtoolbox_1_1metrics_1_1is__metric_3_01base__metric__t_3_01_derived_00_01_element_type_01_4_01_4.html", null ],
        [ "JensenShannonMetric", "classtoolbox_1_1metrics_1_1_jensen_shannon_metric.html", "classtoolbox_1_1metrics_1_1_jensen_shannon_metric" ],
        [ "KLDivergenceMetric", "classtoolbox_1_1metrics_1_1_k_l_divergence_metric.html", "classtoolbox_1_1metrics_1_1_k_l_divergence_metric" ],
        [ "L1Metric", "classtoolbox_1_1metrics_1_1_l1_metric.html", "classtoolbox_1_1metrics_1_1_l1_metric" ],
        [ "L2Metric", "classtoolbox_1_1metrics_1_1_l2_metric.html", "classtoolbox_1_1metrics_1_1_l2_metric" ],
        [ "LambdaMetric", "classtoolbox_1_1metrics_1_1_lambda_metric.html", "classtoolbox_1_1metrics_1_1_lambda_metric" ],
        [ "LinfMetric", "classtoolbox_1_1metrics_1_1_linf_metric.html", "classtoolbox_1_1metrics_1_1_linf_metric" ],
        [ "LpMetric", "classtoolbox_1_1metrics_1_1_lp_metric.html", "classtoolbox_1_1metrics_1_1_lp_metric" ],
        [ "metric_traits", "structtoolbox_1_1metrics_1_1metric__traits.html", "structtoolbox_1_1metrics_1_1metric__traits" ],
        [ "metric_traits< L1Metric< T > >", "structtoolbox_1_1metrics_1_1metric__traits_3_01_l1_metric_3_01_t_01_4_01_4.html", "structtoolbox_1_1metrics_1_1metric__traits_3_01_l1_metric_3_01_t_01_4_01_4" ],
        [ "metric_traits< L2Metric< T > >", "structtoolbox_1_1metrics_1_1metric__traits_3_01_l2_metric_3_01_t_01_4_01_4.html", "structtoolbox_1_1metrics_1_1metric__traits_3_01_l2_metric_3_01_t_01_4_01_4" ],
        [ "MetricFactory", "classtoolbox_1_1metrics_1_1_metric_factory.html", "classtoolbox_1_1metrics_1_1_metric_factory" ],
        [ "MetricRegistry", "classtoolbox_1_1metrics_1_1_metric_registry.html", "classtoolbox_1_1metrics_1_1_metric_registry" ],
        [ "MetricWrapper", "classtoolbox_1_1metrics_1_1_metric_wrapper.html", "classtoolbox_1_1metrics_1_1_metric_wrapper" ],
        [ "ModifiedHausdorffMetric", "classtoolbox_1_1metrics_1_1_modified_hausdorff_metric.html", "classtoolbox_1_1metrics_1_1_modified_hausdorff_metric" ],
        [ "NormalizedAngularMetric", "classtoolbox_1_1metrics_1_1_normalized_angular_metric.html", "classtoolbox_1_1metrics_1_1_normalized_angular_metric" ],
        [ "ParameterizedMetric", "classtoolbox_1_1metrics_1_1_parameterized_metric.html", "classtoolbox_1_1metrics_1_1_parameterized_metric" ],
        [ "PointCloudEMDMetric", "classtoolbox_1_1metrics_1_1_point_cloud_e_m_d_metric.html", "classtoolbox_1_1metrics_1_1_point_cloud_e_m_d_metric" ],
        [ "PointMetricAdapter", "classtoolbox_1_1metrics_1_1_point_metric_adapter.html", "classtoolbox_1_1metrics_1_1_point_metric_adapter" ],
        [ "ScaledMetric", "classtoolbox_1_1metrics_1_1_scaled_metric.html", "classtoolbox_1_1metrics_1_1_scaled_metric" ],
        [ "WeightedMetric", "classtoolbox_1_1metrics_1_1_weighted_metric.html", "classtoolbox_1_1metrics_1_1_weighted_metric" ]
      ] ],
      [ "pcl", "namespacetoolbox_1_1pcl.html", [
        [ "agast_features_extractor_t", "classtoolbox_1_1pcl_1_1agast__features__extractor__t.html", "classtoolbox_1_1pcl_1_1agast__features__extractor__t" ],
        [ "agast_keypoint_extractor_t", "classtoolbox_1_1pcl_1_1agast__keypoint__extractor__t.html", "classtoolbox_1_1pcl_1_1agast__keypoint__extractor__t" ],
        [ "base_descriptor_extractor_t", "classtoolbox_1_1pcl_1_1base__descriptor__extractor__t.html", "classtoolbox_1_1pcl_1_1base__descriptor__extractor__t" ],
        [ "base_keypoint_extractor_t", "classtoolbox_1_1pcl_1_1base__keypoint__extractor__t.html", "classtoolbox_1_1pcl_1_1base__keypoint__extractor__t" ],
        [ "base_knn_generic_t", "classtoolbox_1_1pcl_1_1base__knn__generic__t.html", "classtoolbox_1_1pcl_1_1base__knn__generic__t" ],
        [ "base_knn_t", "classtoolbox_1_1pcl_1_1base__knn__t.html", "classtoolbox_1_1pcl_1_1base__knn__t" ],
        [ "base_norm_extractor_t", "classtoolbox_1_1pcl_1_1base__norm__extractor__t.html", "classtoolbox_1_1pcl_1_1base__norm__extractor__t" ],
        [ "base_signature_t", "structtoolbox_1_1pcl_1_1base__signature__t.html", "structtoolbox_1_1pcl_1_1base__signature__t" ],
        [ "bfknn_generic_t", "classtoolbox_1_1pcl_1_1bfknn__generic__t.html", "classtoolbox_1_1pcl_1_1bfknn__generic__t" ],
        [ "bfknn_parallel_generic_t", "classtoolbox_1_1pcl_1_1bfknn__parallel__generic__t.html", "classtoolbox_1_1pcl_1_1bfknn__parallel__generic__t" ],
        [ "bfknn_parallel_t", "classtoolbox_1_1pcl_1_1bfknn__parallel__t.html", "classtoolbox_1_1pcl_1_1bfknn__parallel__t" ],
        [ "bfknn_t", "classtoolbox_1_1pcl_1_1bfknn__t.html", "classtoolbox_1_1pcl_1_1bfknn__t" ],
        [ "correspondence_generator_t", "classtoolbox_1_1pcl_1_1correspondence__generator__t.html", "classtoolbox_1_1pcl_1_1correspondence__generator__t" ],
        [ "correspondence_t", "structtoolbox_1_1pcl_1_1correspondence__t.html", "structtoolbox_1_1pcl_1_1correspondence__t" ],
        [ "curvature_keypoint_extractor_t", "classtoolbox_1_1pcl_1_1curvature__keypoint__extractor__t.html", "classtoolbox_1_1pcl_1_1curvature__keypoint__extractor__t" ],
        [ "cvfh_extractor_t", "classtoolbox_1_1pcl_1_1cvfh__extractor__t.html", "classtoolbox_1_1pcl_1_1cvfh__extractor__t" ],
        [ "cvfh_signature_t", "structtoolbox_1_1pcl_1_1cvfh__signature__t.html", "structtoolbox_1_1pcl_1_1cvfh__signature__t" ],
        [ "dsc3d_extractor_t", "classtoolbox_1_1pcl_1_1dsc3d__extractor__t.html", "classtoolbox_1_1pcl_1_1dsc3d__extractor__t" ],
        [ "dsc3d_signature_t", "structtoolbox_1_1pcl_1_1dsc3d__signature__t.html", "structtoolbox_1_1pcl_1_1dsc3d__signature__t" ],
        [ "filter_t", "classtoolbox_1_1pcl_1_1filter__t.html", "classtoolbox_1_1pcl_1_1filter__t" ],
        [ "fpfh_extractor_t", "classtoolbox_1_1pcl_1_1fpfh__extractor__t.html", "classtoolbox_1_1pcl_1_1fpfh__extractor__t" ],
        [ "fpfh_signature_t", "structtoolbox_1_1pcl_1_1fpfh__signature__t.html", "structtoolbox_1_1pcl_1_1fpfh__signature__t" ],
        [ "harris3d_keypoint_extractor_t", "classtoolbox_1_1pcl_1_1harris3d__keypoint__extractor__t.html", "classtoolbox_1_1pcl_1_1harris3d__keypoint__extractor__t" ],
        [ "iss_keypoint_extractor_t", "classtoolbox_1_1pcl_1_1iss__keypoint__extractor__t.html", "classtoolbox_1_1pcl_1_1iss__keypoint__extractor__t" ],
        [ "kdtree_generic_t", "classtoolbox_1_1pcl_1_1kdtree__generic__t.html", "classtoolbox_1_1pcl_1_1kdtree__generic__t" ],
        [ "kdtree_t", "classtoolbox_1_1pcl_1_1kdtree__t.html", "classtoolbox_1_1pcl_1_1kdtree__t" ],
        [ "knn_traits", "structtoolbox_1_1pcl_1_1knn__traits.html", "structtoolbox_1_1pcl_1_1knn__traits" ],
        [ "loam_feature_extractor_t", "classtoolbox_1_1pcl_1_1loam__feature__extractor__t.html", "classtoolbox_1_1pcl_1_1loam__feature__extractor__t" ],
        [ "mls_keypoint_extractor_t", "classtoolbox_1_1pcl_1_1mls__keypoint__extractor__t.html", "classtoolbox_1_1pcl_1_1mls__keypoint__extractor__t" ],
        [ "pca_norm_extractor_t", "classtoolbox_1_1pcl_1_1pca__norm__extractor__t.html", "classtoolbox_1_1pcl_1_1pca__norm__extractor__t" ],
        [ "pfh_extractor_t", "classtoolbox_1_1pcl_1_1pfh__extractor__t.html", "classtoolbox_1_1pcl_1_1pfh__extractor__t" ],
        [ "pfh_signature_t", "structtoolbox_1_1pcl_1_1pfh__signature__t.html", "structtoolbox_1_1pcl_1_1pfh__signature__t" ],
        [ "random_downsampling_t", "classtoolbox_1_1pcl_1_1random__downsampling__t.html", "classtoolbox_1_1pcl_1_1random__downsampling__t" ],
        [ "rops_extractor_t", "classtoolbox_1_1pcl_1_1rops__extractor__t.html", "classtoolbox_1_1pcl_1_1rops__extractor__t" ],
        [ "rops_signature_t", "structtoolbox_1_1pcl_1_1rops__signature__t.html", "structtoolbox_1_1pcl_1_1rops__signature__t" ],
        [ "shot_extractor_t", "classtoolbox_1_1pcl_1_1shot__extractor__t.html", "classtoolbox_1_1pcl_1_1shot__extractor__t" ],
        [ "shot_signature_t", "structtoolbox_1_1pcl_1_1shot__signature__t.html", "structtoolbox_1_1pcl_1_1shot__signature__t" ],
        [ "sift3d_keypoint_extractor_t", "classtoolbox_1_1pcl_1_1sift3d__keypoint__extractor__t.html", "classtoolbox_1_1pcl_1_1sift3d__keypoint__extractor__t" ],
        [ "susan_keypoint_extractor_t", "classtoolbox_1_1pcl_1_1susan__keypoint__extractor__t.html", "classtoolbox_1_1pcl_1_1susan__keypoint__extractor__t" ],
        [ "uniform_grid_subsampling_t", "classtoolbox_1_1pcl_1_1uniform__grid__subsampling__t.html", "classtoolbox_1_1pcl_1_1uniform__grid__subsampling__t" ],
        [ "vfh_extractor_t", "classtoolbox_1_1pcl_1_1vfh__extractor__t.html", "classtoolbox_1_1pcl_1_1vfh__extractor__t" ],
        [ "vfh_signature_t", "structtoolbox_1_1pcl_1_1vfh__signature__t.html", "structtoolbox_1_1pcl_1_1vfh__signature__t" ],
        [ "voxel_grid_downsampling_t", "classtoolbox_1_1pcl_1_1voxel__grid__downsampling__t.html", "classtoolbox_1_1pcl_1_1voxel__grid__downsampling__t" ]
      ] ],
      [ "traits", "namespacetoolbox_1_1traits.html", [
        [ "detail", "namespacetoolbox_1_1traits_1_1detail.html", [
          [ "has_type_impl", "structtoolbox_1_1traits_1_1detail_1_1has__type__impl.html", null ],
          [ "has_type_impl< T, void_t< typename T::type > >", "structtoolbox_1_1traits_1_1detail_1_1has__type__impl_3_01_t_00_01void__t_3_01typename_01_t_1_1type_01_4_01_4.html", null ],
          [ "storage_traits", "structtoolbox_1_1traits_1_1detail_1_1storage__traits.html", null ]
        ] ],
        [ "enum_wrapper", "classtoolbox_1_1traits_1_1enum__wrapper.html", "classtoolbox_1_1traits_1_1enum__wrapper" ],
        [ "function_traits", "structtoolbox_1_1traits_1_1function__traits.html", null ],
        [ "function_traits< R(Args...)>", "structtoolbox_1_1traits_1_1function__traits_3_01_r_07_args_8_8_8_08_4.html", "structtoolbox_1_1traits_1_1function__traits_3_01_r_07_args_8_8_8_08_4" ],
        [ "function_traits< R(C::*)(Args...)>", "structtoolbox_1_1traits_1_1function__traits_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_4.html", "structtoolbox_1_1traits_1_1function__traits_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_4" ],
        [ "has_size", "structtoolbox_1_1traits_1_1has__size.html", null ],
        [ "has_size< T, std::void_t< decltype(std::declval< T >().size())> >", "structtoolbox_1_1traits_1_1has__size_3_01_t_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_ae1b1d65497178907f8aa92c18c8ee7d.html", null ],
        [ "has_toString", "structtoolbox_1_1traits_1_1has__to_string.html", null ],
        [ "is_array", "structtoolbox_1_1traits_1_1is__array.html", null ],
        [ "is_callable", "structtoolbox_1_1traits_1_1is__callable.html", null ],
        [ "is_callable< T, std::void_t< decltype(&T::operator())> >", "structtoolbox_1_1traits_1_1is__callable_3_01_t_00_01std_1_1void__t_3_01decltype_07_6_t_1_1operator_07_08_08_4_01_4.html", null ],
        [ "is_const", "structtoolbox_1_1traits_1_1is__const.html", null ],
        [ "is_const_volatile", "structtoolbox_1_1traits_1_1is__const__volatile.html", null ],
        [ "is_function", "structtoolbox_1_1traits_1_1is__function.html", null ],
        [ "is_greater_than_comparable", "structtoolbox_1_1traits_1_1is__greater__than__comparable.html", null ],
        [ "is_greater_than_comparable< T, U, std::void_t< decltype(std::declval< T >() > std::declval< U >())> >", "structtoolbox_1_1traits_1_1is__greater__than__comparable_3_01_t_00_01_u_00_01std_1_1void__t_3_01e12039f554bf02a65bcf2c70b4be1eb1.html", null ],
        [ "is_heap_allocated", "structtoolbox_1_1traits_1_1is__heap__allocated.html", null ],
        [ "is_iterable", "structtoolbox_1_1traits_1_1is__iterable.html", null ],
        [ "is_iterable< T, void_t< decltype(std::begin(std::declval< T >())), decltype(std::end(std::declval< T >()))> >", "structtoolbox_1_1traits_1_1is__iterable_3_01_t_00_01void__t_3_01decltype_07std_1_1begin_07std_1_7117ff6ec554ee2c38ff708913db827f.html", null ],
        [ "is_less_than_comparable", "structtoolbox_1_1traits_1_1is__less__than__comparable.html", null ],
        [ "is_less_than_comparable< T, U, std::void_t< decltype(std::declval< T >()< std::declval< U >())> >", "structtoolbox_1_1traits_1_1is__less__than__comparable_3_01_t_00_01_u_00_01std_1_1void__t_3_01decfcd281f6f40dc9ba8bdb84058aecabad.html", null ],
        [ "is_member_pointer", "structtoolbox_1_1traits_1_1is__member__pointer.html", null ],
        [ "is_null_pointer", "structtoolbox_1_1traits_1_1is__null__pointer.html", null ],
        [ "is_pointer", "structtoolbox_1_1traits_1_1is__pointer.html", null ],
        [ "is_printable", "structtoolbox_1_1traits_1_1is__printable.html", null ],
        [ "is_reference", "structtoolbox_1_1traits_1_1is__reference.html", null ],
        [ "is_stack_allocated", "structtoolbox_1_1traits_1_1is__stack__allocated.html", null ],
        [ "is_volatile", "structtoolbox_1_1traits_1_1is__volatile.html", null ],
        [ "remove_all_qualifiers", "structtoolbox_1_1traits_1_1remove__all__qualifiers.html", "structtoolbox_1_1traits_1_1remove__all__qualifiers" ],
        [ "remove_reference", "structtoolbox_1_1traits_1_1remove__reference.html", "structtoolbox_1_1traits_1_1remove__reference" ],
        [ "type_identity", "structtoolbox_1_1traits_1_1type__identity.html", "structtoolbox_1_1traits_1_1type__identity" ],
        [ "type_list", "structtoolbox_1_1traits_1_1type__list.html", null ]
      ] ],
      [ "types", "namespacetoolbox_1_1types.html", [
        [ "detail", "namespacetoolbox_1_1types_1_1detail.html", [
          [ "is_calculable_container", "structtoolbox_1_1types_1_1detail_1_1is__calculable__container.html", null ],
          [ "is_calculable_container< T, std::void_t< decltype(std::begin(std::declval< const T & >())), decltype(std::end(std::declval< const T & >())), typename T::value_type > >", "structtoolbox_1_1types_1_1detail_1_1is__calculable__container_3_01_t_00_01std_1_1void__t_3_01decca586b4229aea21d85ac37405c05d830.html", null ]
        ] ],
        [ "minmax_t", "structtoolbox_1_1types_1_1minmax__t.html", "structtoolbox_1_1types_1_1minmax__t" ],
        [ "minmax_t< point_t< T > >", "structtoolbox_1_1types_1_1minmax__t_3_01point__t_3_01_t_01_4_01_4.html", "structtoolbox_1_1types_1_1minmax__t_3_01point__t_3_01_t_01_4_01_4" ],
        [ "point_cloud_t", "classtoolbox_1_1types_1_1point__cloud__t.html", "classtoolbox_1_1types_1_1point__cloud__t" ],
        [ "point_t", "structtoolbox_1_1types_1_1point__t.html", "structtoolbox_1_1types_1_1point__t" ]
      ] ],
      [ "utils", "namespacetoolbox_1_1utils.html", [
        [ "detail", "namespacetoolbox_1_1utils_1_1detail.html", [
          [ "has_istream_operator", "structtoolbox_1_1utils_1_1detail_1_1has__istream__operator.html", null ],
          [ "has_istream_operator< T, std::void_t< decltype(std::declval< std::istream & >() > > std::declval< T & >())> >", "structtoolbox_1_1utils_1_1detail_1_1has__istream__operator_3_01_t_00_01std_1_1void__t_3_01decltyb09911d33e7c0cfaf84ec26667d90d9a.html", null ],
          [ "is_optional", "structtoolbox_1_1utils_1_1detail_1_1is__optional.html", null ],
          [ "is_optional< std::optional< U > >", "structtoolbox_1_1utils_1_1detail_1_1is__optional_3_01std_1_1optional_3_01_u_01_4_01_4.html", null ],
          [ "optional_value_type", "structtoolbox_1_1utils_1_1detail_1_1optional__value__type.html", null ],
          [ "optional_value_type< std::optional< U > >", "structtoolbox_1_1utils_1_1detail_1_1optional__value__type_3_01std_1_1optional_3_01_u_01_4_01_4.html", "structtoolbox_1_1utils_1_1detail_1_1optional__value__type_3_01std_1_1optional_3_01_u_01_4_01_4" ]
        ] ],
        [ "ini_detail", "namespacetoolbox_1_1utils_1_1ini__detail.html", [
          [ "has_istream_operator", "structtoolbox_1_1utils_1_1ini__detail_1_1has__istream__operator.html", null ],
          [ "has_istream_operator< T, std::void_t< decltype(std::declval< std::istream & >() > > std::declval< T & >())> >", "structtoolbox_1_1utils_1_1ini__detail_1_1has__istream__operator_3_01_t_00_01std_1_1void__t_3_01d111b8d6ba70747b432a9bed870293f28.html", null ],
          [ "is_optional", "structtoolbox_1_1utils_1_1ini__detail_1_1is__optional.html", null ],
          [ "is_optional< std::optional< U > >", "structtoolbox_1_1utils_1_1ini__detail_1_1is__optional_3_01std_1_1optional_3_01_u_01_4_01_4.html", null ],
          [ "optional_value_type", "structtoolbox_1_1utils_1_1ini__detail_1_1optional__value__type.html", null ],
          [ "optional_value_type< std::optional< U > >", "structtoolbox_1_1utils_1_1ini__detail_1_1optional__value__type_3_01std_1_1optional_3_01_u_01_4_01_4.html", "structtoolbox_1_1utils_1_1ini__detail_1_1optional__value__type_3_01std_1_1optional_3_01_u_01_4_01_4" ]
        ] ],
        [ "argument_t", "classtoolbox_1_1utils_1_1argument__t.html", "classtoolbox_1_1utils_1_1argument__t" ],
        [ "array_printer_t", "classtoolbox_1_1utils_1_1array__printer__t.html", "classtoolbox_1_1utils_1_1array__printer__t" ],
        [ "ClickException", "classtoolbox_1_1utils_1_1_click_exception.html", "classtoolbox_1_1utils_1_1_click_exception" ],
        [ "color_handler_t", "classtoolbox_1_1utils_1_1color__handler__t.html", null ],
        [ "command_t", "classtoolbox_1_1utils_1_1command__t.html", "classtoolbox_1_1utils_1_1command__t" ],
        [ "CommandLineApp", "classtoolbox_1_1utils_1_1_command_line_app.html", "classtoolbox_1_1utils_1_1_command_line_app" ],
        [ "container_printer_t", "classtoolbox_1_1utils_1_1container__printer__t.html", "classtoolbox_1_1utils_1_1container__printer__t" ],
        [ "deque_printer_t", "classtoolbox_1_1utils_1_1deque__printer__t.html", "classtoolbox_1_1utils_1_1deque__printer__t" ],
        [ "flag_t", "classtoolbox_1_1utils_1_1flag__t.html", "classtoolbox_1_1utils_1_1flag__t" ],
        [ "ini_config_t", "classtoolbox_1_1utils_1_1ini__config__t.html", "classtoolbox_1_1utils_1_1ini__config__t" ],
        [ "ini_field_desc", "structtoolbox_1_1utils_1_1ini__field__desc.html", "structtoolbox_1_1utils_1_1ini__field__desc" ],
        [ "ini_struct_traits", "structtoolbox_1_1utils_1_1ini__struct__traits.html", null ],
        [ "list_printer_t", "classtoolbox_1_1utils_1_1list__printer__t.html", "classtoolbox_1_1utils_1_1list__printer__t" ],
        [ "map_printer_t", "classtoolbox_1_1utils_1_1map__printer__t.html", "classtoolbox_1_1utils_1_1map__printer__t" ],
        [ "option_t", "classtoolbox_1_1utils_1_1option__t.html", "classtoolbox_1_1utils_1_1option__t" ],
        [ "parameter_t", "classtoolbox_1_1utils_1_1parameter__t.html", "classtoolbox_1_1utils_1_1parameter__t" ],
        [ "ParameterError", "classtoolbox_1_1utils_1_1_parameter_error.html", "classtoolbox_1_1utils_1_1_parameter_error" ],
        [ "plot_t", "classtoolbox_1_1utils_1_1plot__t.html", "classtoolbox_1_1utils_1_1plot__t" ],
        [ "print_style_t", "structtoolbox_1_1utils_1_1print__style__t.html", "structtoolbox_1_1utils_1_1print__style__t" ],
        [ "queue_printer_t", "classtoolbox_1_1utils_1_1queue__printer__t.html", "classtoolbox_1_1utils_1_1queue__printer__t" ],
        [ "random_t", "classtoolbox_1_1utils_1_1random__t.html", "classtoolbox_1_1utils_1_1random__t" ],
        [ "set_printer_t", "classtoolbox_1_1utils_1_1set__printer__t.html", "classtoolbox_1_1utils_1_1set__printer__t" ],
        [ "simple_timer_array_t", "classtoolbox_1_1utils_1_1simple__timer__array__t.html", "classtoolbox_1_1utils_1_1simple__timer__array__t" ],
        [ "simple_timer_interface_t", "classtoolbox_1_1utils_1_1simple__timer__interface__t.html", "classtoolbox_1_1utils_1_1simple__timer__interface__t" ],
        [ "stop_watch_timer_t", "classtoolbox_1_1utils_1_1stop__watch__timer__t.html", "classtoolbox_1_1utils_1_1stop__watch__timer__t" ],
        [ "table_t", "classtoolbox_1_1utils_1_1table__t.html", "classtoolbox_1_1utils_1_1table__t" ],
        [ "unorderedmap_printer_t", "classtoolbox_1_1utils_1_1unorderedmap__printer__t.html", "classtoolbox_1_1utils_1_1unorderedmap__printer__t" ],
        [ "unorderedset_printer_t", "classtoolbox_1_1utils_1_1unorderedset__printer__t.html", "classtoolbox_1_1utils_1_1unorderedset__printer__t" ],
        [ "UsageError", "classtoolbox_1_1utils_1_1_usage_error.html", "classtoolbox_1_1utils_1_1_usage_error" ],
        [ "vector_printer_t", "classtoolbox_1_1utils_1_1vector__printer__t.html", "classtoolbox_1_1utils_1_1vector__printer__t" ]
      ] ]
    ] ],
    [ "exported_class", "classexported__class.html", "classexported__class" ]
];