var namespacetoolbox_1_1metrics =
[
    [ "AngularMetric", "classtoolbox_1_1metrics_1_1_angular_metric.html", "classtoolbox_1_1metrics_1_1_angular_metric" ],
    [ "base_metric_t", "classtoolbox_1_1metrics_1_1base__metric__t.html", "classtoolbox_1_1metrics_1_1base__metric__t" ],
    [ "BhattacharyyaMetric", "classtoolbox_1_1metrics_1_1_bhattacharyya_metric.html", "classtoolbox_1_1metrics_1_1_bhattacharyya_metric" ],
    [ "BoundingBoxMetric", "classtoolbox_1_1metrics_1_1_bounding_box_metric.html", "classtoolbox_1_1metrics_1_1_bounding_box_metric" ],
    [ "CentroidMetric", "classtoolbox_1_1metrics_1_1_centroid_metric.html", "classtoolbox_1_1metrics_1_1_centroid_metric" ],
    [ "ChamferMetric", "classtoolbox_1_1metrics_1_1_chamfer_metric.html", "classtoolbox_1_1metrics_1_1_chamfer_metric" ],
    [ "ChiSquaredMetric", "classtoolbox_1_1metrics_1_1_chi_squared_metric.html", "classtoolbox_1_1metrics_1_1_chi_squared_metric" ],
    [ "CompositeMetric", "classtoolbox_1_1metrics_1_1_composite_metric.html", "classtoolbox_1_1metrics_1_1_composite_metric" ],
    [ "CorrelationMetric", "classtoolbox_1_1metrics_1_1_correlation_metric.html", "classtoolbox_1_1metrics_1_1_correlation_metric" ],
    [ "CosineMetric", "classtoolbox_1_1metrics_1_1_cosine_metric.html", "classtoolbox_1_1metrics_1_1_cosine_metric" ],
    [ "CustomMetric", "classtoolbox_1_1metrics_1_1_custom_metric.html", "classtoolbox_1_1metrics_1_1_custom_metric" ],
    [ "EMDMetric", "classtoolbox_1_1metrics_1_1_e_m_d_metric.html", "classtoolbox_1_1metrics_1_1_e_m_d_metric" ],
    [ "GeneralizedLpMetric", "classtoolbox_1_1metrics_1_1_generalized_lp_metric.html", "classtoolbox_1_1metrics_1_1_generalized_lp_metric" ],
    [ "HausdorffMetric", "classtoolbox_1_1metrics_1_1_hausdorff_metric.html", "classtoolbox_1_1metrics_1_1_hausdorff_metric" ],
    [ "HellingerMetric", "classtoolbox_1_1metrics_1_1_hellinger_metric.html", "classtoolbox_1_1metrics_1_1_hellinger_metric" ],
    [ "HistogramIntersectionMetric", "classtoolbox_1_1metrics_1_1_histogram_intersection_metric.html", "classtoolbox_1_1metrics_1_1_histogram_intersection_metric" ],
    [ "IMetric", "classtoolbox_1_1metrics_1_1_i_metric.html", "classtoolbox_1_1metrics_1_1_i_metric" ],
    [ "InnerProductMetric", "classtoolbox_1_1metrics_1_1_inner_product_metric.html", "classtoolbox_1_1metrics_1_1_inner_product_metric" ],
    [ "is_metric", "structtoolbox_1_1metrics_1_1is__metric.html", null ],
    [ "is_metric< base_metric_t< Derived, ElementType > >", "structtoolbox_1_1metrics_1_1is__metric_3_01base__metric__t_3_01_derived_00_01_element_type_01_4_01_4.html", null ],
    [ "JensenShannonMetric", "classtoolbox_1_1metrics_1_1_jensen_shannon_metric.html", "classtoolbox_1_1metrics_1_1_jensen_shannon_metric" ],
    [ "KLDivergenceMetric", "classtoolbox_1_1metrics_1_1_k_l_divergence_metric.html", "classtoolbox_1_1metrics_1_1_k_l_divergence_metric" ],
    [ "L1Metric", "classtoolbox_1_1metrics_1_1_l1_metric.html", "classtoolbox_1_1metrics_1_1_l1_metric" ],
    [ "L2Metric", "classtoolbox_1_1metrics_1_1_l2_metric.html", "classtoolbox_1_1metrics_1_1_l2_metric" ],
    [ "LambdaMetric", "classtoolbox_1_1metrics_1_1_lambda_metric.html", "classtoolbox_1_1metrics_1_1_lambda_metric" ],
    [ "LCPMetric", "classtoolbox_1_1metrics_1_1_l_c_p_metric.html", "classtoolbox_1_1metrics_1_1_l_c_p_metric" ],
    [ "LinfMetric", "classtoolbox_1_1metrics_1_1_linf_metric.html", "classtoolbox_1_1metrics_1_1_linf_metric" ],
    [ "LpMetric", "classtoolbox_1_1metrics_1_1_lp_metric.html", "classtoolbox_1_1metrics_1_1_lp_metric" ],
    [ "metric_traits", "structtoolbox_1_1metrics_1_1metric__traits.html", "structtoolbox_1_1metrics_1_1metric__traits" ],
    [ "metric_traits< L1Metric< T > >", "structtoolbox_1_1metrics_1_1metric__traits_3_01_l1_metric_3_01_t_01_4_01_4.html", "structtoolbox_1_1metrics_1_1metric__traits_3_01_l1_metric_3_01_t_01_4_01_4" ],
    [ "metric_traits< L2Metric< T > >", "structtoolbox_1_1metrics_1_1metric__traits_3_01_l2_metric_3_01_t_01_4_01_4.html", "structtoolbox_1_1metrics_1_1metric__traits_3_01_l2_metric_3_01_t_01_4_01_4" ],
    [ "MetricFactory", "classtoolbox_1_1metrics_1_1_metric_factory.html", "classtoolbox_1_1metrics_1_1_metric_factory" ],
    [ "MetricRegistry", "classtoolbox_1_1metrics_1_1_metric_registry.html", "classtoolbox_1_1metrics_1_1_metric_registry" ],
    [ "MetricWrapper", "classtoolbox_1_1metrics_1_1_metric_wrapper.html", "classtoolbox_1_1metrics_1_1_metric_wrapper" ],
    [ "ModifiedHausdorffMetric", "classtoolbox_1_1metrics_1_1_modified_hausdorff_metric.html", "classtoolbox_1_1metrics_1_1_modified_hausdorff_metric" ],
    [ "NormalizedAngularMetric", "classtoolbox_1_1metrics_1_1_normalized_angular_metric.html", "classtoolbox_1_1metrics_1_1_normalized_angular_metric" ],
    [ "ParameterizedMetric", "classtoolbox_1_1metrics_1_1_parameterized_metric.html", "classtoolbox_1_1metrics_1_1_parameterized_metric" ],
    [ "PointCloudEMDMetric", "classtoolbox_1_1metrics_1_1_point_cloud_e_m_d_metric.html", "classtoolbox_1_1metrics_1_1_point_cloud_e_m_d_metric" ],
    [ "PointMetricAdapter", "classtoolbox_1_1metrics_1_1_point_metric_adapter.html", "classtoolbox_1_1metrics_1_1_point_metric_adapter" ],
    [ "ScaledMetric", "classtoolbox_1_1metrics_1_1_scaled_metric.html", "classtoolbox_1_1metrics_1_1_scaled_metric" ],
    [ "WeightedMetric", "classtoolbox_1_1metrics_1_1_weighted_metric.html", "classtoolbox_1_1metrics_1_1_weighted_metric" ],
    [ "metric_ptr", "namespacetoolbox_1_1metrics.html#aa1e717585ad113eed870734e03342f32", null ],
    [ "create_metric", "namespacetoolbox_1_1metrics.html#aef58a1dce41e44c9095da95dc153450f", null ],
    [ "create_metric_for", "namespacetoolbox_1_1metrics.html#ab71d09d8f9b6d58d8f0e3ee2b0ed80cc", null ],
    [ "make_lambda_metric", "namespacetoolbox_1_1metrics.html#a904d2925eefb34b34983b7a8d6130475", null ],
    [ "make_weighted_metric", "namespacetoolbox_1_1metrics.html#a4b4187de154e20f369fd21363cc1ad37", null ],
    [ "has_squared_form_v", "namespacetoolbox_1_1metrics.html#ab4139b55514172f42a4558393cf4895d", null ],
    [ "is_metric_v", "namespacetoolbox_1_1metrics.html#a391eb917db1b77524c70f6e955a110a3", null ],
    [ "is_normalized_metric_v", "namespacetoolbox_1_1metrics.html#a8d0ba347cb51c7b26dcad101204efaab", null ],
    [ "is_symmetric_metric_v", "namespacetoolbox_1_1metrics.html#aed554f345d72f01e40f7b876855dfba1", null ]
];