var type__traits_8hpp =
[
    [ "toolbox::traits::detail::has_type_impl< T, typename >", "structtoolbox_1_1traits_1_1detail_1_1has__type__impl.html", null ],
    [ "toolbox::traits::detail::has_type_impl< T, void_t< typename T::type > >", "structtoolbox_1_1traits_1_1detail_1_1has__type__impl_3_01_t_00_01void__t_3_01typename_01_t_1_1type_01_4_01_4.html", null ],
    [ "toolbox::traits::detail::storage_traits< T >", "structtoolbox_1_1traits_1_1detail_1_1storage__traits.html", null ],
    [ "toolbox::traits::type_identity< T >", "structtoolbox_1_1traits_1_1type__identity.html", "structtoolbox_1_1traits_1_1type__identity" ],
    [ "toolbox::traits::remove_reference< T >", "structtoolbox_1_1traits_1_1remove__reference.html", "structtoolbox_1_1traits_1_1remove__reference" ],
    [ "toolbox::traits::has_toString< T >", "structtoolbox_1_1traits_1_1has__to_string.html", null ],
    [ "toolbox::traits::remove_all_qualifiers< T >", "structtoolbox_1_1traits_1_1remove__all__qualifiers.html", "structtoolbox_1_1traits_1_1remove__all__qualifiers" ],
    [ "toolbox::traits::is_callable< T, typename >", "structtoolbox_1_1traits_1_1is__callable.html", null ],
    [ "toolbox::traits::is_callable< T, std::void_t< decltype(&T::operator())> >", "structtoolbox_1_1traits_1_1is__callable_3_01_t_00_01std_1_1void__t_3_01decltype_07_6_t_1_1operator_07_08_08_4_01_4.html", null ],
    [ "toolbox::traits::type_list< Ts >", "structtoolbox_1_1traits_1_1type__list.html", null ],
    [ "toolbox::traits::function_traits< R(Args...)>", "structtoolbox_1_1traits_1_1function__traits_3_01_r_07_args_8_8_8_08_4.html", "structtoolbox_1_1traits_1_1function__traits_3_01_r_07_args_8_8_8_08_4" ],
    [ "toolbox::traits::function_traits< R(C::*)(Args...)>", "structtoolbox_1_1traits_1_1function__traits_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_4.html", "structtoolbox_1_1traits_1_1function__traits_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_4" ],
    [ "toolbox::traits::has_size< T, typename >", "structtoolbox_1_1traits_1_1has__size.html", null ],
    [ "toolbox::traits::has_size< T, std::void_t< decltype(std::declval< T >().size())> >", "structtoolbox_1_1traits_1_1has__size_3_01_t_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_ae1b1d65497178907f8aa92c18c8ee7d.html", null ],
    [ "toolbox::traits::is_printable< T >", "structtoolbox_1_1traits_1_1is__printable.html", null ],
    [ "toolbox::traits::enum_wrapper< EnumType >", "classtoolbox_1_1traits_1_1enum__wrapper.html", "classtoolbox_1_1traits_1_1enum__wrapper" ],
    [ "toolbox::traits::is_heap_allocated< T >", "structtoolbox_1_1traits_1_1is__heap__allocated.html", null ],
    [ "toolbox::traits::is_stack_allocated< T >", "structtoolbox_1_1traits_1_1is__stack__allocated.html", null ],
    [ "toolbox::traits::is_const< T >", "structtoolbox_1_1traits_1_1is__const.html", null ],
    [ "toolbox::traits::is_volatile< T >", "structtoolbox_1_1traits_1_1is__volatile.html", null ],
    [ "toolbox::traits::is_const_volatile< T >", "structtoolbox_1_1traits_1_1is__const__volatile.html", null ],
    [ "toolbox::traits::is_reference< T >", "structtoolbox_1_1traits_1_1is__reference.html", null ],
    [ "toolbox::traits::is_array< T >", "structtoolbox_1_1traits_1_1is__array.html", null ],
    [ "toolbox::traits::is_function< T >", "structtoolbox_1_1traits_1_1is__function.html", null ],
    [ "toolbox::traits::is_member_pointer< T >", "structtoolbox_1_1traits_1_1is__member__pointer.html", null ],
    [ "toolbox::traits::is_pointer< T >", "structtoolbox_1_1traits_1_1is__pointer.html", null ],
    [ "toolbox::traits::is_null_pointer< T >", "structtoolbox_1_1traits_1_1is__null__pointer.html", null ],
    [ "toolbox::traits::is_iterable< T, typename >", "structtoolbox_1_1traits_1_1is__iterable.html", null ],
    [ "toolbox::traits::is_iterable< T, void_t< decltype(std::begin(std::declval< T >())), decltype(std::end(std::declval< T >()))> >", "structtoolbox_1_1traits_1_1is__iterable_3_01_t_00_01void__t_3_01decltype_07std_1_1begin_07std_1_7117ff6ec554ee2c38ff708913db827f.html", null ],
    [ "toolbox::traits::is_less_than_comparable< T, U, typename >", "structtoolbox_1_1traits_1_1is__less__than__comparable.html", null ],
    [ "toolbox::traits::is_less_than_comparable< T, U, std::void_t< decltype(std::declval< T >()< std::declval< U >())> >", "structtoolbox_1_1traits_1_1is__less__than__comparable_3_01_t_00_01_u_00_01std_1_1void__t_3_01decfcd281f6f40dc9ba8bdb84058aecabad.html", null ],
    [ "toolbox::traits::is_greater_than_comparable< T, U, typename >", "structtoolbox_1_1traits_1_1is__greater__than__comparable.html", null ],
    [ "toolbox::traits::is_greater_than_comparable< T, U, std::void_t< decltype(std::declval< T >() > std::declval< U >())> >", "structtoolbox_1_1traits_1_1is__greater__than__comparable_3_01_t_00_01_u_00_01std_1_1void__t_3_01e12039f554bf02a65bcf2c70b4be1eb1.html", null ],
    [ "void_t", "type__traits_8hpp.html#af947ecd84c1315e86403e59d3508e4f3", null ],
    [ "void_t", "type__traits_8hpp.html#ab78b03f232f72f2deeb66f99ef3d4802", null ],
    [ "is_greater_than_comparable_v", "type__traits_8hpp.html#a597b15e39f8bb17d0a49f8aef59e08ea", null ],
    [ "is_iterable_v", "type__traits_8hpp.html#aff9226c5f441dc4babdc37c493939f40", null ],
    [ "is_less_than_comparable_v", "type__traits_8hpp.html#a9be5bf95dea61ffd682fa0cbdf9a6e3c", null ]
];