var searchData=
[
  ['1_20三层测试架构_0',['2.1 三层测试架构',['../md_docs_2md_2_k_i_t_t_i___t_e_s_t_i_n_g___s_t_r_a_t_e_g_y.html#autotoc_md169',1,'']]],
  ['1_20与pcl工具链集成_1',['5.1 与PCL工具链集成',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md131',1,'']]],
  ['1_20内存映射文件优化_2',['2.1 内存映射文件优化',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md121',1,'']]],
  ['1_20分级错误处理_3',['3.1 分级错误处理',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md125',1,'']]],
  ['1_20单元测试_4',['7.1 单元测试',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md111',1,'']]],
  ['1_20周）_5',['第一阶段：核心算法（第 1 周）',['../md_docs_2md_2_p_r_o_s_a_c___d_e_s_i_g_n.html#autotoc_md196',1,'']]],
  ['1_20基础使用_6',['4.1 基础使用',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md99',1,'']]],
  ['1_20多模态数据同步_7',['4.1 多模态数据同步',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md128',1,'']]],
  ['1_20异常类型_8',['6.1 异常类型',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md108',1,'']]],
  ['1_20描述子距离排序器_9',['1. 描述子距离排序器',['../md_docs_2md_2_c_o_r_r_e_s_p_o_n_d_e_n_c_e___s_o_r_t_e_r___d_e_s_i_g_n.html#autotoc_md76',1,'']]],
  ['1_20架构设计理念_10',['1. 架构设计理念',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md117',1,'']]],
  ['1_20核心数据结构_11',['3.1 核心数据结构',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md94',1,'']]],
  ['1_20核心算法流程_12',['1. 核心算法流程',['../md_docs_2md_2_p_r_o_s_a_c___d_e_s_i_g_n.html#autotoc_md186',1,'']]],
  ['1_20概述_13',['1. 概述',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md88',1,'']]],
  ['1_20测试挑战_14',['1. 测试挑战',['../md_docs_2md_2_k_i_t_t_i___t_e_s_t_i_n_g___s_t_r_a_t_e_g_y.html#autotoc_md167',1,'']]],
  ['1_20类型命名_20type_20naming_15',['1. 类型命名 / Type Naming',['../md_docs_2md_2_c_o_d_e___s_t_y_l_e.html#autotoc_md48',1,'']]],
  ['1_20缓存策略_16',['5.1 缓存策略',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md104',1,'']]],
  ['1_20计算优化_17',['1. 计算优化',['../md_docs_2md_2_p_r_o_s_a_c___d_e_s_i_g_n.html#autotoc_md208',1,'']]],
  ['1_201_20分层架构设计_18',['1.1 分层架构设计',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md118',1,'']]],
  ['1_202_20组合优于继承_19',['1.2 组合优于继承',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md119',1,'']]],
  ['1_20api设计原则_20',['6.1 API设计原则',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md134',1,'']]],
  ['1_20kitti_20odometry格式_21',['2.1 KITTI Odometry格式',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md90',1,'']]],
  ['1_20mock数据生成器_22',['3.1 Mock数据生成器',['../md_docs_2md_2_k_i_t_t_i___t_e_s_t_i_n_g___s_t_r_a_t_e_g_y.html#autotoc_md171',1,'']]],
  ['10天）_23',['Phase 4: 集成和测试（第9-10天）',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md140',1,'']]],
  ['10_20代码风格示例_20style_20example_24',['10. 代码风格示例 / Style Example',['../md_docs_2md_2_c_o_d_e___s_t_y_l_e.html#autotoc_md66',1,'']]],
  ['10_3a_20文档完善_25',['Day 10: 文档完善',['../md_docs_2md_2_k_i_t_t_i___i_m_p_l_e_m_e_n_t_a_t_i_o_n___p_l_a_n.html#autotoc_md159',1,'']]],
  ['11_20备注_20notes_26',['11. 备注 / Notes',['../md_docs_2md_2_c_o_d_e___s_t_y_l_e.html#autotoc_md68',1,'']]],
  ['1_3a_20基础设施建设（2天）_27',['Phase 1: 基础设施建设（2天）',['../md_docs_2md_2_k_i_t_t_i___i_m_p_l_e_m_e_n_t_a_t_i_o_n___p_l_a_n.html#autotoc_md145',1,'']]],
  ['1_3a_20数据结构和类型定义_28',['Day 1: 数据结构和类型定义',['../md_docs_2md_2_k_i_t_t_i___i_m_p_l_e_m_e_n_t_a_t_i_o_n___p_l_a_n.html#autotoc_md146',1,'']]],
  ['1_3a_20核心功能（第1_203天）_29',['Phase 1: 核心功能（第1-3天）',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md137',1,'']]]
];
