var searchData=
[
  ['3天）_0',['Phase 1: 核心功能（第1-3天）',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md137',1,'']]],
  ['3_20与dataloader集成_1',['4.3 与DataLoader集成',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md101',1,'']]],
  ['3_20具体测试方案_2',['3. 具体测试方案',['../md_docs_2md_2_k_i_t_t_i___t_e_s_t_i_n_g___s_t_r_a_t_e_g_y.html#autotoc_md170',1,'']]],
  ['3_20内存优化_3',['3. 内存优化',['../md_docs_2md_2_p_r_o_s_a_c___d_e_s_i_g_n.html#autotoc_md210',1,'']]],
  ['3_20变换估计_4',['3. 变换估计',['../md_docs_2md_2_p_r_o_s_a_c___d_e_s_i_g_n.html#autotoc_md190',1,'']]],
  ['3_20周）_5',['第三阶段：质量度量和优化（第 3 周）',['../md_docs_2md_2_p_r_o_s_a_c___d_e_s_i_g_n.html#autotoc_md198',1,'']]],
  ['3_20并行处理_6',['5.3 并行处理',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md106',1,'']]],
  ['3_20并行数据加载_7',['2.3 并行数据加载',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md123',1,'']]],
  ['3_20性能测试_8',['7.3 性能测试',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md113',1,'']]],
  ['3_20成员变量与成员函数_20members_9',['3. 成员变量与成员函数 / Members',['../md_docs_2md_2_c_o_d_e___s_t_y_l_e.html#autotoc_md52',1,'']]],
  ['3_20数据格式说明_10',['2.3 数据格式说明',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md92',1,'']]],
  ['3_20架构设计_11',['3. 架构设计',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md93',1,'']]],
  ['3_20组合排序器_12',['3. 组合排序器',['../md_docs_2md_2_c_o_r_r_e_s_p_o_n_d_e_n_c_e___s_o_r_t_e_r___d_e_s_i_g_n.html#autotoc_md78',1,'']]],
  ['3_20错误处理和恢复_13',['3. 错误处理和恢复',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md124',1,'']]],
  ['3_201_20分级错误处理_14',['3.1 分级错误处理',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md125',1,'']]],
  ['3_201_20核心数据结构_15',['3.1 核心数据结构',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md94',1,'']]],
  ['3_201_20mock数据生成器_16',['3.1 Mock数据生成器',['../md_docs_2md_2_k_i_t_t_i___t_e_s_t_i_n_g___s_t_r_a_t_e_g_y.html#autotoc_md171',1,'']]],
  ['3_202_20单元测试示例_17',['3.2 单元测试示例',['../md_docs_2md_2_k_i_t_t_i___t_e_s_t_i_n_g___s_t_r_a_t_e_g_y.html#autotoc_md172',1,'']]],
  ['3_202_20数据验证层_18',['3.2 数据验证层',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md126',1,'']]],
  ['3_202_20辅助组件_19',['3.2 辅助组件',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md95',1,'']]],
  ['3_203_20性能基准测试_20',['3.3 性能基准测试',['../md_docs_2md_2_k_i_t_t_i___t_e_s_t_i_n_g___s_t_r_a_t_e_g_y.html#autotoc_md173',1,'']]],
  ['3_203_20数据集类_21',['3.3 数据集类',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md96',1,'']]],
  ['3_204_20工具函数_22',['3.4 工具函数',['../md_docs_2md_2_k_i_t_t_i___d_a_t_a_s_e_t___l_o_a_d_e_r___d_e_s_i_g_n.html#autotoc_md97',1,'']]],
  ['3_204_20集成测试（可选）_23',['3.4 集成测试（可选）',['../md_docs_2md_2_k_i_t_t_i___t_e_s_t_i_n_g___s_t_r_a_t_e_g_y.html#autotoc_md174',1,'']]],
  ['3_205_20测试数据最小化策略_24',['3.5 测试数据最小化策略',['../md_docs_2md_2_k_i_t_t_i___t_e_s_t_i_n_g___s_t_r_a_t_e_g_y.html#autotoc_md175',1,'']]],
  ['3_3a_20基础kitti数据集_25',['Day 3: 基础KITTI数据集',['../md_docs_2md_2_k_i_t_t_i___i_m_p_l_e_m_e_n_t_a_t_i_o_n___p_l_a_n.html#autotoc_md149',1,'']]],
  ['3_3a_20高级特性（第7_208天）_26',['Phase 3: 高级特性（第7-8天）',['../md_docs_2md_2_k_i_t_t_i___d_e_e_p___i_m_p_l_e_m_e_n_t_a_t_i_o_n___i_n_s_i_g_h_t_s.html#autotoc_md139',1,'']]],
  ['3_3a_20semantic_20kitti支持（2天）_27',['Phase 3: Semantic KITTI支持（2天）',['../md_docs_2md_2_k_i_t_t_i___i_m_p_l_e_m_e_n_t_a_t_i_o_n___p_l_a_n.html#autotoc_md152',1,'']]],
  ['3dsc_5fextractor_2ehpp_28',['3dsc_extractor.hpp',['../3dsc__extractor_8hpp.html',1,'']]],
  ['3dsc_5fextractor_5fold_2ehpp_29',['3dsc_extractor_old.hpp',['../3dsc__extractor__old_8hpp.html',1,'']]]
];
