name: Update Master Docs

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update -q
          && sudo apt-get install doxygen make -q -y && mkdir -p build/docs

      - name: Build docs
        run: make docs

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/html
          publish_branch: gh-pages-latest
